### ISSUE TITLE
Dell-Optiplex-780-OC-EFI-Catalina

### ISSUE THREAD

**Issue by Enmanuel265** [osx86-ijb/Dell-Optiplex-780-OC-EFI-Catalina#1]
You can make a document with the instructions to follow for this opencore efi and you can describe in which version the system is working, you can give the instructions to create usb boot for this

**Comment by osx86-ijb** [comment]
https://dortania.github.io/OpenCore-Install-Guide/ contains all of the information that's needed to create a bootable USB installer, as well as the instructions for playing an OpenCore EFI onto an ESP partition. 🤓
