### ISSUE TITLE
BIOS Configuration and Installer Boot Problem

### ISSUE THREAD

**Issue by ag03-recoveryacc** [osx86-ijb/Dell-Optiplex-780-OC-EFI-Catalina#2]
Hi,
I recently created bootable USB Stick using Rufus method and made folder with macrecovery files for Catalina on it. 
Next I placed your EFI files too and I tried to boot Catalina installer but after selecting USB Sandisk Stick as primary Boot device I see communicate: 

"Alert! Failed to detect one or more drives during POST.
Strike the F1 key to continue, F2 to run the setup utility
Press F5 to run onboard diagnostics"

After pressing F1 after few times I hear Beep every press.
I tried to run diagnostics but it was OK.

PC SPECS:
DELL OptiPlex 780 SFF
CPU: Intel Core 2 Quad (if I remember correctly it's Q6600)
GPU: MSI Nvidia GT 710 2GB
RAM: 8GB DDR3 1066MHz
SSD: WD Green 240GB SATA III
LAN and Audio same as in repository Readme.

![223530729_257175159551122_2463220029472873403_n](https://user-images.githubusercontent.com/87917062/126883136-6418057b-febd-471f-8fdb-75138888f285.jpg)

**Comment by osx86-ijb** [comment]
This doesn't have anything to do with my EFI. This is an issue with BIOS settings, physical drive settings, or the way the EFI partition was created on the USB.

I will be marking this as closed, as it doesn't have anything to do with the files that I've provided, as they themselves are operational. The issues that you are having are related to things other than the EFI files that I've provided. 

May I suggest double checking the double check as well as the things that I've mentioned previously, as I'm quite certain that it's related to one of those three things that I mentioned.
