### ISSUE TITLE
CMOS reset

### ISSUE THREAD

**Issue by komeloo** [osx86-ijb/Dell-Optiplex-780-OC-EFI-Catalina#3]
The OC file works, but the only problem is that everytime after rebooting, the CMOS reset, then have to goto BIOS again to re-config. (I have 2 Dell 780 and both have the same issue).

**Comment by osx86-ijb** [comment]
The CMOS batteries needed replacing. This doesn’t have anything to do with
the EFI posted here, as it is operational and works.
